### ISSUE TITLE
Modifications to custom format are not immediately available

### ISSUE THREAD

**Issue by sergburn** [HaaLeo/vscode-timing#16]
After adding new custom format in User Settings, or editing existing format, it is not available in palette. For example, Now->Custom does not show the format at all. 
Then after editing the format Epoch->Custom shows old format and does not do any conversion. 

The format I first tried was:

        {
            "format": "DD-MMM-YYYY HH:mm:ss.SSS"
        }

It was not visible in Now->Custom

Then I edited it to 

        {
            "format": "DD-MM-YYYY"
        }

Now Epoch->Custom shows the previous format, Now->Custom still offers nothing.
Custom-><Anything> does not show updated format either. I also tried to add it to Workspace Settings, but without success.

What do I do wrong?

**Comment by HaaLeo** [comment]
Thank you for the report. This is indeed a bug. The `_items` of the `QuickpickStep` are only updated when the extension is started, but not when the settings are updated. 
Until I figured out a fix for this you can run the command `Reload Window` as a workaround. This will make the Extension to update the formats.

**Comment by HaaLeo** [comment]
published in version 1.1.1
