### ISSUE TITLE
Directly convert between custom formats

### ISSUE THREAD

**Issue by Arcovion** [HaaLeo/vscode-timing#19]
My use case is just converting hand written dates like so: `10 Apr 2015` -> `2015-04-10`
It would be nice to have a `Custom -> Custom` option so you don't have to first convert to epoch and then to the format you want.

Also, it would be useful if we could define our own commands: I'd like to make a command that will do `DD MMM Y -> Y-MM-DD` straight away without navigating the menus. I don't know if that's possible though.

Finally, it would be nice to hide the result view altogether, instead of having to press enter. Once the date
is inserted, I don't really need the ability to go back and change my choice, or re-insert the date with the pencil icon. On the rare chance I've picked the wrong choice, I'd rather just Ctrl+Z and re-enter the command again.

P.S. Is there a way to hide commands from the commend palette in VSCode? I won't be using durations, the full length ISO8601 format, the 'toggle insert converted time' command... in fact I won't personally need *any* of them if there is a `Custom -> Custom` option.

**Comment by HaaLeo** [comment]
@Arcovion thank you for your comprehensive feedback/feature request. I derive 4 main requests:
1. Add a `Custom to Custom` command
1. Enable users to define their own commands to abreviate the options selection.  
    * for instance to skip the insertion of the epoch unit in the `*toEpoch` commands or format insertion in commands that use a custom pattern.
1. When the `timing.insertConvertedTime` option is set to `true` the result view should not be shown.
1. Command visibility: Enable the user to set which commands are not shown in the command palette. As far as I know you cannot set the visibility of commands within vscode by default.

I will create a single issue for each of those requests and close this one instead.
