### ISSUE TITLE
Support negative epoch timestamps

### ISSUE THREAD

**Issue by nukaboy** [HaaLeo/vscode-timing#59]
At the moment, dates from before 1970 can be converted into a negative epoch, i would like for the reverse to be also supported.

**Comment by HaaLeo** [comment]
released with v2.7.0

**Comment by StefanBrand** [comment]
Unfortunately this change breaks the extension for me. Consider a Docker tag like this:

`master-1646914900-1adac459`

## Version 2.6.0

>>>
Epoch Unit: s
UTC Timestamp: 2022-03-10T12:21:40.000Z
>>>

## Version 2.7.0

>>>
Epoch Unit: s
UTC Timestamp: 1917-10-24T11:38:20.000Z
>>>

I will stick to 2.6.0 for now.

**Comment by HaaLeo** [comment]
Hi @StefanBrand thx for your comment. I was not aware of such side effects. Maybe the parsing pattern could be moved to a setting in a future release. Than people could individually adjust the pattern according to their needs.
