### ISSUE TITLE
When hovering over us timestamp, it displays incorrect time

### ISSUE THREAD

**Issue by joshabb** [HaaLeo/vscode-timing#60]
| VS Code Version | vscode-timing Version | Operating System |
| --------------- | --------------------- | ---------------- |
|  1.63.1               |     2.6.0                  |         Ubuntu 21.04         |

# Description
When hovering over the timestamp 1630588240938140, it displays January 19, 1970. It says it recognizes that this date is in microseconds.

## Expected Behavior
In reality, this timestamp should be displayed as September 2, 2021. 

## Actual Behavior
It is saying that this timestamp is sometime in 1970. If I delete the last three digits of the timestamp (1630588240938) it gets the correct date as it uses milliseconds as the input.

# Steps to Reproduce

1. Put 1630588240938140 in a txt file
2. Hover over it
3. Observe incorrect human time

# Settings
<details><pre><code>

"timing.hoverTimestamp.targetFormat": [
        "local",
        "utc",
        "MM/DD/YYYY HH:mm:ss.SSS"
    ],
</code></pre></details>

**Comment by joshabb** [comment]
As a side note nanaseconds do not work (i.e., 1630588240938140000). Seconds DO work (i.e., 1630588240).

**Comment by HaaLeo** [comment]
Hi @joshabb thx for your bug report. I can reproduce the behavior and will investigate a possible fix.

**Comment by HaaLeo** [comment]
released with v2.7.0
